FROM node:22.12-alpine3.21
LABEL authors="RuVl_13"

# Set enviroment variables
ENV TZ Europe/Moscow

# Prepare project directory
WORKDIR /app

# Copy and install dependencies
COPY package.json ./
RUN npm install --verbose

# Copy project to directory
COPY . .

# Run app
ENTRYPOINT exec npm run dev