FROM node:24.2.0
LABEL authors="RuVl_13"

# Set enviroment variables
ENV TZ Europe/Moscow

# Prepare project directory
CMD mkdir -p /usr/src/app/
WORKDIR /usr/src/app/

# Copy and install dependencies
COPY ./package.json ./
RUN npm install --verbose

# Copy project to directory
COPY . ./

# Run app
ENTRYPOINT exec npm run dev