volumes:
  postgres_volume:  # Volume for database
    driver: local
  products_volume:  # Volume for product files
    driver: local
  static_volume:  # Volume with django static for serving by nginx
    driver: local

networks:
  verdoc:
    driver: bridge

services:
  frontend-nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - "80:80"
      - "443:443"
    networks:
      - verdoc
    depends_on:
      - backend

  postgres:
    image: postgres:16.2
    restart: unless-stopped
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file: postgres/.env
    expose:
      - 5432
    networks:
      - verdoc
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - products_volume:/usr/src/app/products
      - static_volume:/usr/src/app/static
    env_file:
      - backend/.env
      - postgres/.env  # For db connection
    expose:
      - 8000
    networks:
      - verdoc
    depends_on:
      postgres:
        condition: service_healthy
