# Generated by Django 6.0.6 on 2026-07-30 08:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("access_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("access_token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_subscribed", models.BooleanField(default=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["email"],
            },
        ),
    ]
