# Generated by Django 6.0.6 on 2026-08-06 15:46

from django.db import migrations, models


def existing_customers_speak_russian(apps, schema_editor):
    """
    Everyone who bought before this release got their e-mail in Russian, hard-coded.

    The field default is the site default (`en`), which would silently switch their language
    on the next mail; this keeps them where they were until they tell us otherwise.
    """

    apps.get_model("customer", "Customer").objects.update(language="ru")


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="language",
            field=models.CharField(choices=[("en", "English"), ("ru", "Russian")], default="en", max_length=5),
        ),
        migrations.RunPython(existing_customers_speak_russian, migrations.RunPython.noop),
    ]
