# Generated by Django 5.0.7 on 2024-07-15 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passport",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passports",
                to="passport.country",
            ),
        ),
    ]
