# Generated by Django 5.0.7 on 2024-07-15 20:20

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("passport", "0002_alter_passport_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passport",
            name="price",
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency="USD", max_digits=10),
        ),
        migrations.AlterField(
            model_name="passport",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("RUB", "Russian Ruble"), ("USD", "US Dollar")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
    ]
