# Generated by Django 5.0.7 on 2024-07-15 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport", "0003_alter_passport_price_alter_passport_price_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="passport",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PassportFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_path", models.FileField(unique=True, upload_to="passports/")),
                (
                    "passport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="passport.passport",
                    ),
                ),
            ],
        ),
    ]
