# Generated by Django 5.0.7 on 2024-07-16 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("passport", "0004_passport_quantity_passportfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passport",
            name="quantity",
        ),
    ]
