# Generated by Django 5.0.7 on 2024-07-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport", "0005_remove_passport_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="passport",
            name="quantity",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
