# Generated by Django 5.0.7 on 2024-07-26 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport", "0006_passport_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passportfile",
            name="passport",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="passport.passport",
            ),
        ),
    ]
