# Generated by Django 5.0.7 on 2024-07-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport", "0007_alter_passportfile_passport"),
    ]

    operations = [
        migrations.AddField(
            model_name="passportfile",
            name="status",
            field=models.CharField(
                choices=[("IN_STOCK", "In stock"), ("RESERVED", "Reserved"), ("SOLD", "Sold")],
                default="IN_STOCK",
                editable=False,
                max_length=20,
            ),
        ),
    ]
