# Generated by Django 5.0.7 on 2024-08-02 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("passport", "0008_passportfile_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"], "verbose_name": "Country", "verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="passport",
            options={"ordering": ["name"], "verbose_name": "Passport", "verbose_name_plural": "Passports"},
        ),
        migrations.AlterModelOptions(
            name="passportfile",
            options={
                "ordering": ["passport", "file_path"],
                "verbose_name": "Passport File",
                "verbose_name_plural": "Passport Files",
            },
        ),
    ]
