# Generated by Django 5.0.7 on 2024-08-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport", "0009_alter_country_options_alter_passport_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passportfile",
            name="file_path",
            field=models.FileField(unique=True, upload_to="products/passports/"),
        ),
    ]
