# Generated by Django 5.2.4 on 2026-07-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport", "0010_alter_passportfile_file_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passport",
            name="quantity",
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name="In stock"),
        ),
    ]
