# Generated by Django 6.0.6 on 2026-07-30 10:01

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("OVERPAID", "Overpaid"),
                            ("EXPIRED", "Expired"),
                            ("ERROR", "Error"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "total_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("RUB", "Russian Ruble"), ("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total_price",
                    djmoney.models.fields.MoneyField(decimal_places=2, default_currency="USD", max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="customer.customer"
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=255)),
                (
                    "unit_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("RUB", "Russian Ruble"), ("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "unit_price",
                    djmoney.models.fields.MoneyField(decimal_places=2, default_currency="USD", max_digits=10),
                ),
                ("unit_price_usd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="sales.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order item",
                "verbose_name_plural": "Order items",
            },
        ),
        migrations.CreateModel(
            name="PaymentCallbackLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("txn_id", models.CharField(blank=True, max_length=100, null=True)),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="callback_logs",
                        to="sales.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment callback",
                "verbose_name_plural": "Payment callbacks",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("txn_id", models.CharField(max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=10, max_digits=20)),
                ("currency", models.CharField(max_length=10)),
                ("pending_amount", models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ("tx_urls", models.JSONField(blank=True, null=True)),
                (
                    "source_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("RUB", "Russian Ruble"), ("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "source_price",
                    djmoney.models.fields.MoneyField(
                        blank=True, decimal_places=2, default_currency="USD", max_digits=10, null=True
                    ),
                ),
                ("source_rate", models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ("commission", models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("pending", "Pending"),
                            ("pending internal", "Pending Internal"),
                            ("expired", "Expired"),
                            ("completed", "Completed"),
                            ("mismatch", "Mismatch"),
                            ("error", "Error"),
                            ("cancelled", "Cancelled"),
                            ("cancelled duplicate", "Cancelled Duplicate"),
                        ],
                        default="new",
                        max_length=30,
                    ),
                ),
                ("confirmations", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("merchant", models.CharField(blank=True, max_length=127, null=True)),
                ("merchant_id", models.CharField(blank=True, max_length=63, null=True)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="sales.order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state",
                    models.CharField(
                        choices=[("RESERVED", "Reserved"), ("DELIVERED", "Delivered"), ("RELEASED", "Released")],
                        default="RESERVED",
                        max_length=15,
                    ),
                ),
                ("reserved_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("token", models.UUIDField(blank=True, null=True, unique=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stock_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocations",
                        to="catalog.stockitem",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="allocations", to="sales.orderitem"
                    ),
                ),
            ],
            options={
                "verbose_name": "Allocation",
                "verbose_name_plural": "Allocations",
                "ordering": ["-reserved_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("state", "RELEASED"), _negated=True),
                        fields=("stock_item",),
                        name="one_active_allocation_per_stock_item",
                    )
                ],
            },
        ),
    ]
