# Generated by Django 6.0.6 on 2026-07-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_transfer_from_legacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
