# Generated by Django 6.0.6 on 2026-08-03 11:56

from django.db import migrations, models

import sales.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("sales", "0003_order_invoice_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocation",
            name="stock_item",
            field=models.ForeignKey(
                null=True,
                on_delete=sales.models.protect_held_units,
                related_name="allocations",
                to="catalog.stockitem",
            ),
        ),
    ]
