# Generated by Django 5.0.7 on 2024-07-26 16:00

import uuid

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("passport", "0007_alter_passportfile_passport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("OVERPAID", "Overpaid"),
                            ("EXPIRED", "Expired"),
                            ("ERROR", "Error"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "total_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("RUB", "Russian Ruble"), ("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total_price",
                    djmoney.models.fields.MoneyField(decimal_places=2, default_currency="USD", max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order.order",
                    ),
                ),
                (
                    "passport",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="passport.passport"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DownloadLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_path",
                    models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="passport.passportfile"),
                ),
                ("order_item", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="order.orderitem")),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("txn_id", models.CharField(blank=True, max_length=100, null=True)),
                ("amount", models.DecimalField(decimal_places=10, max_digits=20)),
                ("currency", models.CharField(max_length=10)),
                (
                    "source_price_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("RUB", "Russian Ruble"), ("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "source_price",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        default_currency="USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("source_rate", models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("pending", "Pending"),
                            ("pending internal", "Pending Internal"),
                            ("expired", "Expired"),
                            ("completed", "Completed"),
                            ("mismatch", "Mismatch"),
                            ("error", "Error"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("confirmations", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("commission", models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction",
                        to="order.order",
                    ),
                ),
            ],
        ),
    ]
