# Generated by Django 5.0.7 on 2024-07-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="downloadlink",
            old_name="file_path",
            new_name="passport_file",
        ),
        migrations.RemoveField(
            model_name="downloadlink",
            name="created_at",
        ),
        migrations.AddField(
            model_name="downloadlink",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
