# Generated by Django 5.0.7 on 2024-08-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_rename_file_path_downloadlink_passport_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant_id",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
