# Generated by Django 5.0.7 on 2024-08-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_transaction_comment_transaction_merchant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_reserved",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
