# Generated by Django 5.2.4 on 2026-07-02 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_orderitem_is_reserved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadlink",
            name="order_item",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="order.orderitem"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("OVERPAID", "Overpaid"),
                    ("EXPIRED", "Expired"),
                    ("ERROR", "Error"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("pending", "Pending"),
                    ("pending internal", "Pending Internal"),
                    ("expired", "Expired"),
                    ("completed", "Completed"),
                    ("mismatch", "Mismatch"),
                    ("error", "Error"),
                    ("cancelled", "Cancelled"),
                    ("cancelled duplicate", "Cancelled Duplicate"),
                ],
                default="new",
                max_length=30,
            ),
        ),
    ]
