# Generated by Django 5.2.16 on 2026-07-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="broadcast",
            name="body_html",
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="body",
            field=models.TextField(help_text="HTML email body"),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="test_email",
            field=models.EmailField(blank=True, help_text="Address for the 'Send test email' action", max_length=254),
        ),
    ]
