# Generated by Django 6.0.6 on 2026-08-06 15:54

from django.db import migrations

# Nothing is carried over: this app never reached production, so the table is always empty.
# Opting out now lives on Customer.is_subscribed / unsubscribed_at (see ADR-0004 and R3).


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0002_remove_broadcast_body_html_alter_broadcast_body_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Unsubscribe",
        ),
    ]
