# Generated by Django 6.0.6 on 2026-08-06 15:57

import django.db.models.deletion
from django.db import migrations, models

# The counters leave with no data migration: they only ever described a run of the previous
# sender, and the app has never been in production. From here on they are derived from the
# BroadcastDelivery rows this migration creates.


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_customer_language"),
        ("mailing", "0003_delete_unsubscribe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="broadcast",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Broadcast",
                "verbose_name_plural": "Broadcasts",
            },
        ),
        migrations.RemoveField(model_name="broadcast", name="error_log"),
        migrations.RemoveField(model_name="broadcast", name="failed_count"),
        migrations.RemoveField(model_name="broadcast", name="sent_count"),
        migrations.RemoveField(model_name="broadcast", name="total_recipients"),
        migrations.CreateModel(
            name="BroadcastDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("SENT", "Sent"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="mailing.broadcast",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_deliveries",
                        to="customer.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Broadcast delivery",
                "verbose_name_plural": "Broadcast deliveries",
                "ordering": ["broadcast", "customer"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("broadcast", "customer"),
                        name="one_delivery_per_broadcast_customer",
                    )
                ],
            },
        ),
    ]
