# Generated by Django 6.0.6 on 2026-08-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0004_alter_broadcast_options_remove_broadcast_error_log_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="body_en",
            field=models.TextField(help_text="HTML email body", null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="body_ru",
            field=models.TextField(help_text="HTML email body", null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="subject_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="subject_ru",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
